apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: host-local-tools
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: host-local-tools
  template:
    metadata:
      labels:
        name: host-local-tools
    spec:
      containers:
      - name: host-local-tools
        image: host-local-tools
        volumeMounts:
        - name: cnfpath
          mountPath: /opt/cni/example.conf
        - name: varlog
          mountPath: /var/log
        - name: appini
          mountPath: /opt/host-local-tools/resource/app.ini
          subPath: app.ini
        - name: template-json
          mountPath: /opt/host-local-tools/resource/host-local-template.json
          subPath: host-local-template.json
#      nodeSelector:
#        rdma: support
      volumes:
      - name: varlog
        hostPath:
          path: /opt/01master.cnf
      - name: varlog
        hostPath:
          path: /var/log/
      - name: appini
        configMap:
          name: host-local-tools
          items:
          - key: app.ini
            path: app.ini
      - name: template-json
        configMap:
          name: host-local-tools
          items:
          - key: host-local-template.json
            path: host-local-template.json